# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import re


class Ui_window(object):

    def calculations(self):
        text = window.sender().text()
        dispText = self.displayLabel.text()
        
        if text == "=":

            # if "%" in dispText:
            #     n = dispText.count("%")
            #     for i in range(n):
            #         print(re.split(r" + - * /", dispText))
            # return


            value = eval(dispText.replace("X", "*"))
            if value == int(value):
                value = int(value)
            # print(value)
            self.displayLabel.setText(str(value)[:10])
            return

        if text == "C":
            self.displayLabel.setText("0")
            return

        if text == "➙":
            # print(f"{dispText[:-1]=}")
            if dispText[:-1] == "":
                self.displayLabel.setText("0")
                return

            if dispText != "0":
                self.displayLabel.setText(dispText[:-1])
                return

        if text == "+/-":
            if dispText[0] != "-":
                self.displayLabel.setText("-" + dispText)
                return
            self.displayLabel.setText(dispText[1:])

        if text in "+-X/%" and len(dispText) > 0 and dispText[-1] in "+-X/%":
            if dispText[-1] == text:
                return
            self.displayLabel.setText(dispText[:-1] + text)
            return

        if dispText == "0":
            if text in "+-X/%":
                return
            if text != ".":
                self.displayLabel.setText("")

        if text.isdigit() or text not in ["C", "➙", "+/-", "="]:
            self.displayLabel.setText(self.displayLabel.text() + text)

    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.displayLabel = QtWidgets.QLabel(self.centralwidget)
        self.displayLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(36)
        self.displayLabel.setFont(font)
        self.displayLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.displayLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.displayLabel.setLineWidth(2)
        self.displayLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayLabel.setObjectName("displayLabel")
        self.bper = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bper.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bper.setFont(font)
        self.bper.setObjectName("bper")
        self.bC = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bC.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bC.setFont(font)
        self.bC.setObjectName("bC")
        self.bdiv = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bdiv.setGeometry(QtCore.QRect(280, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bdiv.setFont(font)
        self.bdiv.setObjectName("bdiv")
        self.bback = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bback.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.bback.setFont(font)
        self.bback.setObjectName("bback")
        self.b8 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b8.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b9.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.bmulti = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bmulti.setGeometry(QtCore.QRect(280, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bmulti.setFont(font)
        self.bmulti.setObjectName("bmulti")
        self.b7 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b7.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.b4 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b4.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.bminus = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bminus.setGeometry(QtCore.QRect(280, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bminus.setFont(font)
        self.bminus.setObjectName("bminus")
        self.b5 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b5.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b6.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.b1 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b1.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.bplus = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bplus.setGeometry(QtCore.QRect(280, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bplus.setFont(font)
        self.bplus.setObjectName("bplus")
        self.b2 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b2.setGeometry(QtCore.QRect(100, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b3.setGeometry(QtCore.QRect(190, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.bunary = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bunary.setGeometry(QtCore.QRect(10, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bunary.setFont(font)
        self.bunary.setObjectName("bunary")
        self.bequal = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bequal.setGeometry(QtCore.QRect(280, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bequal.setFont(font)
        self.bequal.setObjectName("bequal")
        self.b0 = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.b0.setGeometry(QtCore.QRect(100, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setObjectName("b0")
        self.bdecimal = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculations)
        self.bdecimal.setGeometry(QtCore.QRect(190, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typewriter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bdecimal.setFont(font)
        self.bdecimal.setObjectName("bdecimal")
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 22))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Calculator"))
        self.displayLabel.setText(_translate("window", "0"))
        self.bper.setText(_translate("window", "%"))
        self.bC.setText(_translate("window", "C"))
        self.bdiv.setText(_translate("window", "/"))
        self.bback.setText(_translate("window", "➙"))
        self.b8.setText(_translate("window", "8"))
        self.b9.setText(_translate("window", "9"))
        self.bmulti.setText(_translate("window", "X"))
        self.b7.setText(_translate("window", "7"))
        self.b4.setText(_translate("window", "4"))
        self.bminus.setText(_translate("window", "-"))
        self.b5.setText(_translate("window", "5"))
        self.b6.setText(_translate("window", "6"))
        self.b1.setText(_translate("window", "1"))
        self.bplus.setText(_translate("window", "+"))
        self.b2.setText(_translate("window", "2"))
        self.b3.setText(_translate("window", "3"))
        self.bunary.setText(_translate("window", "+/-"))
        self.bequal.setText(_translate("window", "="))
        self.b0.setText(_translate("window", "0"))
        self.bdecimal.setText(_translate("window", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
